/**
 * PDF Generator Service
 *
 * Generates PDF reports from SecurityReport data using jsPDF
 * Feature: enhanced-security-scanner
 * Requirements: 1.1, 1.2, 1.3, 1.5
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { SecurityReport, Vulnerability, ActionPlanItem } from '../types/security-report.types';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
  interface jsPDF {
    lastAutoTable?: { finalY: number };
  }
}

export interface PDFGeneratorOptions {
  language: 'tr' | 'en';
  includeExecutiveSummary: boolean;
  includeRemediation: boolean;
}

export interface PDFGenerationResult {
  success: boolean;
  blob?: Blob;
  error?: string;
}

// Severity color mapping (RGB values)
const SEVERITY_COLORS: Record<string, [number, number, number]> = {
  'Kritik': [220, 53, 69],      // Red
  'Critical': [220, 53, 69],
  'Yüksek': [253, 126, 20],     // Orange
  'High': [253, 126, 20],
  'Orta': [255, 193, 7],        // Yellow
  'Medium': [255, 193, 7],
  'Düşük': [40, 167, 69],       // Green
  'Low': [40, 167, 69],
  'Bilgi': [23, 162, 184],      // Cyan
  'Info': [23, 162, 184]
};

// Translations for PDF content
const PDF_TRANSLATIONS = {
  tr: {
    title: 'Güvenlik Tarama Raporu',
    executiveSummary: 'Yönetici Özeti',
    targetUrl: 'Hedef URL',
    scanDate: 'Tarama Tarihi',
    securityScore: 'Güvenlik Puanı',
    summary: 'Özet',
    vulnerabilities: 'Tespit Edilen Zafiyetler',
    vulnerability: 'Zafiyet',
    severity: 'Önem Derecesi',
    location: 'Konum',
    description: 'Açıklama',
    remediation: 'Çözüm Önerisi',
    cvssScore: 'CVSS Puanı',
    actionPlan: 'Eylem Planı',
    task: 'Görev',
    priority: 'Öncelik',
    effort: 'Efor',
    estimatedTime: 'Tahmini Süre',
    delayImpact: 'Gecikme Etkisi',
    networkInfo: 'Ağ Bilgileri',
    ipAddress: 'IP Adresi',
    location_label: 'Konum',
    isp: 'ISP',
    asn: 'ASN',
    organization: 'Organizasyon',
    serverType: 'Sunucu Tipi',
    openPorts: 'Açık Portlar',
    techStack: 'Teknoloji Yığını',
    technology: 'Teknoloji',
    risks: 'Riskler',
    compliance: 'Uyumluluk Durumu',
    standard: 'Standart',
    status: 'Durum',
    details: 'Detaylar',
    sslInfo: 'SSL/TLS Bilgileri',
    issuer: 'Sertifika Sağlayıcı',
    validFrom: 'Geçerlilik Başlangıcı',
    validTo: 'Geçerlilik Bitişi',
    daysRemaining: 'Kalan Gün',
    protocol: 'Protokol',
    grade: 'Derece',
    generatedBy: 'Bu rapor SecuriScan AI tarafından oluşturulmuştur.',
    page: 'Sayfa',
    noVulnerabilities: 'Zafiyet tespit edilmedi.',
    noActionPlan: 'Eylem planı mevcut değil.',
    priorityUrgent: 'ACİL',
    priorityHigh: 'YÜKSEK',
    priorityMedium: 'ORTA',
    effortLow: 'DÜŞÜK',
    effortMedium: 'ORTA',
    effortHigh: 'YÜKSEK',
    // Error messages (Requirement 1.5)
    errorGeneration: 'PDF oluşturulurken bir hata oluştu',
    errorInvalidReport: 'Geçersiz rapor verisi',
    errorMemory: 'Rapor çok büyük, PDF oluşturulamadı',
    errorUnknown: 'Bilinmeyen bir hata oluştu'
  },
  en: {
    title: 'Security Scan Report',
    executiveSummary: 'Executive Summary',
    targetUrl: 'Target URL',
    scanDate: 'Scan Date',
    securityScore: 'Security Score',
    summary: 'Summary',
    vulnerabilities: 'Detected Vulnerabilities',
    vulnerability: 'Vulnerability',
    severity: 'Severity',
    location: 'Location',
    description: 'Description',
    remediation: 'Remediation',
    cvssScore: 'CVSS Score',
    actionPlan: 'Action Plan',
    task: 'Task',
    priority: 'Priority',
    effort: 'Effort',
    estimatedTime: 'Estimated Time',
    delayImpact: 'Delay Impact',
    networkInfo: 'Network Information',
    ipAddress: 'IP Address',
    location_label: 'Location',
    isp: 'ISP',
    asn: 'ASN',
    organization: 'Organization',
    serverType: 'Server Type',
    openPorts: 'Open Ports',
    techStack: 'Technology Stack',
    technology: 'Technology',
    risks: 'Risks',
    compliance: 'Compliance Status',
    standard: 'Standard',
    status: 'Status',
    details: 'Details',
    sslInfo: 'SSL/TLS Information',
    issuer: 'Certificate Issuer',
    validFrom: 'Valid From',
    validTo: 'Valid To',
    daysRemaining: 'Days Remaining',
    protocol: 'Protocol',
    grade: 'Grade',
    generatedBy: 'This report was generated by SecuriScan AI.',
    page: 'Page',
    noVulnerabilities: 'No vulnerabilities detected.',
    noActionPlan: 'No action plan available.',
    priorityUrgent: 'URGENT',
    priorityHigh: 'HIGH',
    priorityMedium: 'MEDIUM',
    effortLow: 'LOW',
    effortMedium: 'MEDIUM',
    effortHigh: 'HIGH',
    // Error messages (Requirement 1.5)
    errorGeneration: 'An error occurred while generating the PDF',
    errorInvalidReport: 'Invalid report data',
    errorMemory: 'Report is too large to generate PDF',
    errorUnknown: 'An unknown error occurred'
  }
};

/**
 * Get severity color for table cells
 */
function getSeverityColor(severity: string): [number, number, number] {
  return SEVERITY_COLORS[severity] || [128, 128, 128];
}

/**
 * Format date for display
 */
function formatDate(dateString: string, lang: 'tr' | 'en'): string {
  try {
    const date = new Date(dateString);
    return date.toLocaleDateString(lang === 'tr' ? 'tr-TR' : 'en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  } catch {
    return dateString;
  }
}

/**
 * Get score color based on value
 */
function getScoreColor(score: number): [number, number, number] {
  if (score >= 80) return [40, 167, 69];    // Green
  if (score >= 60) return [255, 193, 7];    // Yellow
  if (score >= 40) return [253, 126, 20];   // Orange
  return [220, 53, 69];                      // Red
}

/**
 * Translate priority value
 */
function translatePriority(priority: string, lang: 'tr' | 'en'): string {
  const t = PDF_TRANSLATIONS[lang];
  switch (priority) {
    case 'URGENT': return t.priorityUrgent;
    case 'HIGH': return t.priorityHigh;
    case 'MEDIUM': return t.priorityMedium;
    default: return priority;
  }
}

/**
 * Translate effort value
 */
function translateEffort(effort: string, lang: 'tr' | 'en'): string {
  const t = PDF_TRANSLATIONS[lang];
  switch (effort) {
    case 'LOW': return t.effortLow;
    case 'MEDIUM': return t.effortMedium;
    case 'HIGH': return t.effortHigh;
    default: return effort;
  }
}


/**
 * PDF Generator class
 */
export class PDFGenerator {
  private doc: jsPDF;
  private lang: 'tr' | 'en';
  private t: typeof PDF_TRANSLATIONS['tr'];
  private currentY: number = 20;
  private pageWidth: number;
  private pageHeight: number;
  private margin: number = 20;

  constructor(lang: 'tr' | 'en' = 'tr') {
    this.doc = new jsPDF('p', 'mm', 'a4');
    this.lang = lang;
    this.t = PDF_TRANSLATIONS[lang];
    this.pageWidth = this.doc.internal.pageSize.getWidth();
    this.pageHeight = this.doc.internal.pageSize.getHeight();
  }

  /**
   * Generate PDF from security report
   * Requirement 1.5: Error handling with user-friendly messages
   */
  async generate(report: SecurityReport): Promise<PDFGenerationResult> {
    try {
      // Validate report data
      if (!report || !report.targetUrl) {
        return { success: false, error: this.t.errorInvalidReport };
      }

      this.addHeader(report);
      this.addExecutiveSummary(report);
      this.addVulnerabilityTable(report.vulnerabilities);
      this.addActionPlan(report.actionPlan);
      this.addNetworkInfo(report);
      this.addTechStack(report);
      this.addComplianceSection(report);
      this.addSSLInfo(report);
      this.addFooter();

      const blob = this.doc.output('blob');
      return { success: true, blob };
    } catch (error) {
      // Requirement 1.5: Display localized error message to user
      let errorMessage = this.t.errorUnknown;
      
      if (error instanceof Error) {
        // Check for specific error types
        if (error.message.includes('memory') || error.message.includes('size')) {
          errorMessage = this.t.errorMemory;
        } else {
          errorMessage = `${this.t.errorGeneration}: ${error.message}`;
        }
      }
      
      return { success: false, error: errorMessage };
    }
  }

  /**
   * Check if we need a new page
   */
  private checkPageBreak(requiredSpace: number = 30): void {
    if (this.currentY + requiredSpace > this.pageHeight - 20) {
      this.doc.addPage();
      this.currentY = 20;
    }
  }

  /**
   * Add section title
   */
  private addSectionTitle(title: string): void {
    this.checkPageBreak(20);
    this.doc.setFontSize(14);
    this.doc.setTextColor(30, 41, 59);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(title, this.margin, this.currentY);
    this.currentY += 8;
    
    // Add underline
    this.doc.setDrawColor(59, 130, 246);
    this.doc.setLineWidth(0.5);
    this.doc.line(this.margin, this.currentY - 2, this.pageWidth - this.margin, this.currentY - 2);
    this.currentY += 5;
  }

  /**
   * Add header with title and basic info
   */
  private addHeader(report: SecurityReport): void {
    // Title
    this.doc.setFontSize(24);
    this.doc.setTextColor(30, 41, 59);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(this.t.title, this.pageWidth / 2, this.currentY, { align: 'center' });
    this.currentY += 15;

    // Target URL
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(100, 100, 100);
    this.doc.text(`${this.t.targetUrl}: ${report.targetUrl}`, this.pageWidth / 2, this.currentY, { align: 'center' });
    this.currentY += 6;

    // Scan date
    this.doc.text(`${this.t.scanDate}: ${formatDate(report.scanTimestamp, this.lang)}`, this.pageWidth / 2, this.currentY, { align: 'center' });
    this.currentY += 15;

    // Horizontal line
    this.doc.setDrawColor(200, 200, 200);
    this.doc.setLineWidth(0.3);
    this.doc.line(this.margin, this.currentY, this.pageWidth - this.margin, this.currentY);
    this.currentY += 10;
  }

  /**
   * Add executive summary section
   */
  private addExecutiveSummary(report: SecurityReport): void {
    this.addSectionTitle(this.t.executiveSummary);

    // Security Score Box
    const scoreBoxX = this.margin;
    const scoreBoxY = this.currentY;
    const scoreBoxWidth = 50;
    const scoreBoxHeight = 25;

    const scoreColor = getScoreColor(report.overallScore);
    this.doc.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    this.doc.roundedRect(scoreBoxX, scoreBoxY, scoreBoxWidth, scoreBoxHeight, 3, 3, 'F');

    this.doc.setFontSize(20);
    this.doc.setTextColor(255, 255, 255);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(`${report.overallScore}`, scoreBoxX + scoreBoxWidth / 2, scoreBoxY + 15, { align: 'center' });

    this.doc.setFontSize(8);
    this.doc.text(this.t.securityScore, scoreBoxX + scoreBoxWidth / 2, scoreBoxY + 21, { align: 'center' });

    // Summary text
    this.doc.setFontSize(10);
    this.doc.setTextColor(60, 60, 60);
    this.doc.setFont('helvetica', 'normal');
    
    const summaryX = scoreBoxX + scoreBoxWidth + 10;
    const summaryWidth = this.pageWidth - summaryX - this.margin;
    const summaryLines = this.doc.splitTextToSize(report.summary || '', summaryWidth);
    this.doc.text(summaryLines, summaryX, scoreBoxY + 8);

    this.currentY = scoreBoxY + Math.max(scoreBoxHeight, summaryLines.length * 5) + 15;
  }

  /**
   * Add vulnerability table with severity colors
   */
  private addVulnerabilityTable(vulnerabilities: Vulnerability[]): void {
    this.addSectionTitle(this.t.vulnerabilities);

    if (!vulnerabilities || vulnerabilities.length === 0) {
      this.doc.setFontSize(10);
      this.doc.setTextColor(100, 100, 100);
      this.doc.text(this.t.noVulnerabilities, this.margin, this.currentY);
      this.currentY += 15;
      return;
    }

    const tableData = vulnerabilities.map(vuln => [
      vuln.title,
      vuln.severity,
      vuln.location,
      vuln.cvssScore.toFixed(1),
      vuln.remediation.substring(0, 60) + (vuln.remediation.length > 60 ? '...' : '')
    ]);

    autoTable(this.doc, {
      startY: this.currentY,
      head: [[this.t.vulnerability, this.t.severity, this.t.location, this.t.cvssScore, this.t.remediation]],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: [30, 41, 59],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9
      },
      bodyStyles: {
        fontSize: 8,
        cellPadding: 3
      },
      columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 25 },
        2: { cellWidth: 35 },
        3: { cellWidth: 20 },
        4: { cellWidth: 50 }
      },
      didParseCell: (data) => {
        // Color severity column
        if (data.section === 'body' && data.column.index === 1) {
          const severity = data.cell.raw as string;
          const color = getSeverityColor(severity);
          data.cell.styles.textColor = color;
          data.cell.styles.fontStyle = 'bold';
        }
      },
      margin: { left: this.margin, right: this.margin }
    });

    this.currentY = (this.doc.lastAutoTable?.finalY || this.currentY) + 15;
  }


  /**
   * Add action plan section
   */
  private addActionPlan(actionPlan: ActionPlanItem[]): void {
    this.checkPageBreak(40);
    this.addSectionTitle(this.t.actionPlan);

    if (!actionPlan || actionPlan.length === 0) {
      this.doc.setFontSize(10);
      this.doc.setTextColor(100, 100, 100);
      this.doc.text(this.t.noActionPlan, this.margin, this.currentY);
      this.currentY += 15;
      return;
    }

    const tableData = actionPlan.map((item, index) => [
      (index + 1).toString(),
      item.task,
      translatePriority(item.priority, this.lang),
      translateEffort(item.effort, this.lang),
      item.estimatedTime,
      item.delayImpact.substring(0, 40) + (item.delayImpact.length > 40 ? '...' : '')
    ]);

    autoTable(this.doc, {
      startY: this.currentY,
      head: [[
        '#',
        this.t.task,
        this.t.priority,
        this.t.effort,
        this.t.estimatedTime,
        this.t.delayImpact
      ]],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: [30, 41, 59],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9
      },
      bodyStyles: {
        fontSize: 8,
        cellPadding: 3
      },
      columnStyles: {
        0: { cellWidth: 10 },
        1: { cellWidth: 50 },
        2: { cellWidth: 25 },
        3: { cellWidth: 20 },
        4: { cellWidth: 25 },
        5: { cellWidth: 40 }
      },
      didParseCell: (data) => {
        // Color priority column
        if (data.section === 'body' && data.column.index === 2) {
          const priority = data.cell.raw as string;
          if (priority === this.t.priorityUrgent) {
            data.cell.styles.textColor = [220, 53, 69];
            data.cell.styles.fontStyle = 'bold';
          } else if (priority === this.t.priorityHigh) {
            data.cell.styles.textColor = [253, 126, 20];
            data.cell.styles.fontStyle = 'bold';
          }
        }
      },
      margin: { left: this.margin, right: this.margin }
    });

    this.currentY = (this.doc.lastAutoTable?.finalY || this.currentY) + 15;
  }

  /**
   * Add network information section
   */
  private addNetworkInfo(report: SecurityReport): void {
    if (!report.networkInfo) return;

    this.checkPageBreak(50);
    this.addSectionTitle(this.t.networkInfo);

    const networkData = [
      [this.t.ipAddress, report.networkInfo.ip || 'N/A'],
      [this.t.location_label, report.networkInfo.location || 'N/A'],
      [this.t.isp, report.networkInfo.isp || 'N/A'],
      [this.t.asn, report.networkInfo.asn || 'N/A'],
      [this.t.organization, report.networkInfo.organization || 'N/A'],
      [this.t.serverType, report.networkInfo.serverType || 'N/A'],
      [this.t.openPorts, (report.networkInfo.ports || []).join(', ') || 'N/A']
    ];

    autoTable(this.doc, {
      startY: this.currentY,
      body: networkData,
      theme: 'plain',
      bodyStyles: {
        fontSize: 9,
        cellPadding: 3
      },
      columnStyles: {
        0: { cellWidth: 50, fontStyle: 'bold', textColor: [60, 60, 60] },
        1: { cellWidth: 120 }
      },
      margin: { left: this.margin, right: this.margin }
    });

    this.currentY = (this.doc.lastAutoTable?.finalY || this.currentY) + 15;
  }

  /**
   * Add technology stack section
   */
  private addTechStack(report: SecurityReport): void {
    if (!report.techStackDetected || report.techStackDetected.length === 0) return;

    this.checkPageBreak(40);
    this.addSectionTitle(this.t.techStack);

    const techData = report.techStackDetected.map(tech => [
      tech.name,
      tech.description,
      tech.commonRisks.map(r => r.name).join(', ') || 'N/A'
    ]);

    autoTable(this.doc, {
      startY: this.currentY,
      head: [[this.t.technology, this.t.description, this.t.risks]],
      body: techData,
      theme: 'striped',
      headStyles: {
        fillColor: [30, 41, 59],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9
      },
      bodyStyles: {
        fontSize: 8,
        cellPadding: 3
      },
      columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 70 },
        2: { cellWidth: 60 }
      },
      margin: { left: this.margin, right: this.margin }
    });

    this.currentY = (this.doc.lastAutoTable?.finalY || this.currentY) + 15;
  }

  /**
   * Add compliance section
   */
  private addComplianceSection(report: SecurityReport): void {
    if (!report.compliance || report.compliance.length === 0) return;

    this.checkPageBreak(40);
    this.addSectionTitle(this.t.compliance);

    const complianceData = report.compliance.map(item => [
      item.standard,
      item.status,
      item.details
    ]);

    autoTable(this.doc, {
      startY: this.currentY,
      head: [[this.t.standard, this.t.status, this.t.details]],
      body: complianceData,
      theme: 'striped',
      headStyles: {
        fillColor: [30, 41, 59],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9
      },
      bodyStyles: {
        fontSize: 8,
        cellPadding: 3
      },
      columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 30 },
        2: { cellWidth: 100 }
      },
      didParseCell: (data) => {
        // Color status column
        if (data.section === 'body' && data.column.index === 1) {
          const status = data.cell.raw as string;
          if (status === 'PASS') {
            data.cell.styles.textColor = [40, 167, 69];
            data.cell.styles.fontStyle = 'bold';
          } else if (status === 'FAIL') {
            data.cell.styles.textColor = [220, 53, 69];
            data.cell.styles.fontStyle = 'bold';
          } else if (status === 'WARNING') {
            data.cell.styles.textColor = [255, 193, 7];
            data.cell.styles.fontStyle = 'bold';
          }
        }
      },
      margin: { left: this.margin, right: this.margin }
    });

    this.currentY = (this.doc.lastAutoTable?.finalY || this.currentY) + 15;
  }

  /**
   * Add SSL/TLS information section
   */
  private addSSLInfo(report: SecurityReport): void {
    if (!report.ssl) return;

    this.checkPageBreak(50);
    this.addSectionTitle(this.t.sslInfo);

    const sslData = [
      [this.t.issuer, report.ssl.issuer || 'N/A'],
      [this.t.validFrom, report.ssl.validFrom || 'N/A'],
      [this.t.validTo, report.ssl.validTo || 'N/A'],
      [this.t.daysRemaining, report.ssl.daysRemaining?.toString() || 'N/A'],
      [this.t.protocol, report.ssl.protocol || 'N/A'],
      [this.t.grade, report.ssl.grade || 'N/A']
    ];

    autoTable(this.doc, {
      startY: this.currentY,
      body: sslData,
      theme: 'plain',
      bodyStyles: {
        fontSize: 9,
        cellPadding: 3
      },
      columnStyles: {
        0: { cellWidth: 50, fontStyle: 'bold', textColor: [60, 60, 60] },
        1: { cellWidth: 120 }
      },
      didParseCell: (data) => {
        // Color grade
        if (data.section === 'body' && data.row.index === 5 && data.column.index === 1) {
          const grade = data.cell.raw as string;
          if (grade === 'A+' || grade === 'A') {
            data.cell.styles.textColor = [40, 167, 69];
          } else if (grade === 'B') {
            data.cell.styles.textColor = [255, 193, 7];
          } else if (grade === 'C' || grade === 'D') {
            data.cell.styles.textColor = [253, 126, 20];
          } else if (grade === 'F') {
            data.cell.styles.textColor = [220, 53, 69];
          }
          data.cell.styles.fontStyle = 'bold';
        }
      },
      margin: { left: this.margin, right: this.margin }
    });

    this.currentY = (this.doc.lastAutoTable?.finalY || this.currentY) + 15;
  }

  /**
   * Add footer to all pages
   */
  private addFooter(): void {
    const pageCount = this.doc.getNumberOfPages();
    
    for (let i = 1; i <= pageCount; i++) {
      this.doc.setPage(i);
      
      // Footer line
      this.doc.setDrawColor(200, 200, 200);
      this.doc.setLineWidth(0.3);
      this.doc.line(this.margin, this.pageHeight - 15, this.pageWidth - this.margin, this.pageHeight - 15);
      
      // Footer text
      this.doc.setFontSize(8);
      this.doc.setTextColor(150, 150, 150);
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(this.t.generatedBy, this.margin, this.pageHeight - 10);
      this.doc.text(`${this.t.page} ${i} / ${pageCount}`, this.pageWidth - this.margin, this.pageHeight - 10, { align: 'right' });
    }
  }
}

/**
 * Generate PDF from security report
 * Main export function for external use
 */
export async function generatePDF(
  report: SecurityReport,
  lang: 'tr' | 'en' = 'tr'
): Promise<PDFGenerationResult> {
  const generator = new PDFGenerator(lang);
  return generator.generate(report);
}

export default PDFGenerator;
